# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: 'Herbrand Street Apartment'
header: home
email: herbrandapartment@gmail.com
author: Anya
description: 'Spacious 2 bedroom apartment in central london available for tourists. Located close to British Museum. Perfect place for holidays in London.'
copyright: 'Copyright &copy; 2018 TaniaStronaInternetu. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

sass:
    sass_dir: _sass

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: details
    url: '#about'
    icon: angle-double-down
  - title: book
    url: https://www.homeaway.co.uk/p471112
    icon: calendar
